### PR TITLE
Merging Python Style guide Repository

### PR DESCRIPTION
**Pull request by fsan**
This PR moves the content from https://github.com/cookpad/python-style-guide to `global-style-guides` to open source Cookpad best-practices related to Python development.

### CODE REVIEW

**Comment by bermannoah** [comment]
I still don't understand why this PR is porting over the commit history from the other repo – don't we just need the 'final product' - in this case the markdown doc?

**Comment by fsan** [comment]
> I still don't understand why this PR is porting over the commit history from the other repo – don't we just need the 'final product' - in this case the markdown doc?

👇   That's one of the reasons

> Working to add a feature to change weight of title boosting instead of disabling
Merging python style guide to global-style-guides public repository

**Comment by bermannoah** [comment]
Got it!

**Review by robertomiranda — APPROVED** [review]
LGTM thanks @fsan 🎉 

remember to create a merge commit instead of squash, to keep the git history 👍

**Review by bermannoah — APPROVED** [review]
LGTM! Thanks, sorry for all the hassle 😅

**Comment by bermannoah** [comment]
@fsan should be enabled now

**Pull request merged**
