### PR TITLE
Forbid Negated If syntax

### PR DESCRIPTION
**Pull request by davidstosik**
This would detect the _Bad_ examples below:

```rb
# Bad
if !condition
  do_something
end

# Good
unless condition
  do_something
end

# Good
if opposite_condition
  do_something
end

# Bad
do_something if !condition

# Good
do_something unless opposite_condition

# Bad
do_something unless !condition

# Good
do_something if opposite_condition
```

### CODE REVIEW

**Comment by balvig** [comment]
Initial impression is that this sounds good, but was wondering if it might be worth as an exercise considering what the impact would be on some existing examples in our code base?

Grep'ing revealed a handful of examples, here's a sample:

```rb
if !paginating? && recipes.any?
```

```rb
      if queued?
        :queued
      elsif row_count.nil?
        :new
      elsif !user_ids_result_is_fetched?
        :counted
      elsif user_ids_result_is_fetched?
        :fetched
      end
```

```rb
    if !dry_run? && unsafe?
      imageable.censor_image
    end
```

**Comment by davidstosik** [comment]
Alright, give me some time to check what I'll get.

**Comment by davidstosik** [comment]
@balvig 
I added the cop to `global-web`'s `.rubocop.yml` file
```diff
diff --git i/.rubocop.yml w/.rubocop.yml
index 7fc03579da..02b4c2bd34 100644
--- i/.rubocop.yml
+++ w/.rubocop.yml
@@ -24,3 +24,6 @@ Rails/UnknownEnv:
 Rails/HttpPositionalArguments:
   Exclude:
     -  spec/requests/api/**/*
+
+Style/NegatedIf:
+  Enabled: both

```

The run RuboCop to focus on this specific cop:
```sh
rubocop -c .rubocop.yml --only Style/NegatedIf
```

Here is the result:
```
Inspecting 2393 files
(...)
Offenses:

app/controllers/admin/moderation/notes_controller.rb:24:9: C: Style/NegatedIf: Favor unless over if for negative conditions.                                  
        redirect_back fallback_location: admin_root_url if !request.xhr?
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/initializers/fix_fk_rails.rb:47:13: C: Style/NegatedIf: Favor unless over if for negative conditions.                                                  
            if !FK_NAME_IGNORE_PATTERN.match?(foreign_key.name) ...
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/initializers/feature_toggles.rb:38:3: C: Style/NegatedIf: Favor unless over if for negative conditions.                                                
  return true if !Rails.env.production?
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/initializers/feature_toggles.rb:237:3: C: Style/NegatedIf: Favor unless over if for negative conditions.                                               
  return true if !Rails.env.production?
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/initializers/feature_toggles.rb:467:3: C: Style/NegatedIf: Favor unless over if for negative conditions.                                               
  return true if !Rails.env.production?
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/initializers/feature_toggles.rb:506:3: C: Style/NegatedIf: Favor unless over if for negative conditions.                                               
  return true if !Rails.env.production?
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/initializers/feature_toggles.rb:514:3: C: Style/NegatedIf: Favor unless over if for negative conditions.                                               
  return true if !Rails.env.production?
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/initializers/feature_toggles.rb:546:3: C: Style/NegatedIf: Favor unless over if for negative conditions.                                               
  return false if !Experiment.enabled?(:achievement_with_badges)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/initializers/feature_toggles.rb:618:3: C: Style/NegatedIf: Favor unless over if for negative conditions.                                               
  return true if !Rails.env.production?
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/commands/oneoffs/example_command.rb:18:1: E: Lint/Syntax: unexpected token $end                                                                           
(Using Ruby 2.5 parser; configure using TargetRubyVersion parameter, under AllCops)                                                                           

2393 files inspected, 10 offenses detected
```

That does not seem to be catching the examples you grepped above.
I had a quick look yesterday at how RuboCop works, and specifically the `NegatedIf` cop and the parsing loging, and as far as I understand, it only triggers on `if` statements where the whole condition is negated.
It does not apply to `if !a && b`, but it would apply to `if !(a || b)`.

**Comment by sebasoga** [comment]
:+1:

**Pull request merged**
